export const PHOTO = 'PHOTO'
export const NAME = 'NAME'
export const AGE = 'AGE'
export const LANGUAGE = 'LANGUAGE'
export const INTEREST = 'INTEREST'

export const START_FETCHING_WISHLIST = 'START_FETCHING_WISHLIST'
export const SUCCESS_FETCHING = 'SUCCESS_FETCHING'
export const FAIL_TO_FETCH_WISHLIST = 'FAIL_TO_FETCH_WISHLIST'


export const CURRENT_USER = 'CURRENT_USER'