export const USER_INPUT_HANDLER = 'USER_INPUT_HANDLER'
export const ISREDIRECT = 'ISREDIRECT'
export const ISSUBMITTED = 'ISSUBMITTED'
export const CHECK = 'CHECK'

export const SUCCESS_TO_FETCH_CHILD = 'SUCCESS_TO_FETCH_CHILD'
export const START_FETCHING_CHILD = 'START_FETCHING_CHILD'
export const FAIL_TO_FETCH_CHILD = 'FAIL_TO_FETCH_CHILD'

export const START_FETCHING_WISHLIST = 'START_FETCHING_WISHLIST'
export const SUCCESS_FETCHING = 'SUCCESS_FETCHING'
export const FAIL_TO_FETCH_WISHLIST = 'FAIL_TO_FETCH_WISHLIST'

export const CURRENT_USER = 'CURRENT_USER'

/////// MESSAGE AFTER SIGNUP AND FORGOT PASSWORD
export const SIGNUP_AND_FORGOT_MESSAGE = 'SIGNUP_AND_FORGOT_MESSAGE'

//////////USER
export const TOKEN = 'TOKEN'
export const SAVE_CHILD = 'SAVE_CHILD'
